import{PublicClientApplication,InteractionRequiredAuthError}from"@azure/msal-browser";
import{appendTaskRecord,WORKBOOK_FILE_NAME,WORKBOOK_MIME}from"./workbook-append.js";
import"./app-config.js";
import"./styles.css";

const CONFIG=window.QUICK_CAPTURE_CONFIG,SCOPES=CONFIG.GRAPH_SCOPES||["Files.ReadWrite.AppFolder"],DRAFT_KEY="quick-capture-pending-v1",DEVICE_KEY="quick-capture-device-v1";
const CATEGORIES=["防衛","収益","能力","構造","探索","ルーティン","その他"],PRIORITIES=["🔥HOT","🟠WARM","🧊COLD"];
const state={msal:null,account:null,mode:"",busy:false,pending:readPending()};
const $=id=>document.getElementById(id);

document.querySelector("#app").innerHTML=`<main class="app-shell"><header><div class="brand-mark">QC</div><div><h1>QUICK CAPTURE <small>V1</small></h1><p>TASK CONTROLへ送る</p></div><button id="accountBtn" class="account-btn" type="button">Microsoftログイン</button></header><section id="choice" class="choice"><button type="button" data-mode="memo"><span class="mode-icon">▤</span><b>メモ</b><small>外部メモとして送る</small></button><button type="button" data-mode="task"><span class="mode-icon">✓</span><b>タスク</b><small>必要項目を入力して送る</small></button></section><section id="capture" class="capture hidden"><div class="capture-head"><button id="backBtn" type="button" aria-label="戻る">←</button><div><h2 id="modeTitle"></h2><p id="modeGuide"></p></div></div><form id="captureForm"><div id="memoFields" class="memo-fields hidden"><label>メモ<textarea name="memo" rows="12" maxlength="2000" placeholder="ここにメモを入力"></textarea></label></div><div id="taskFields" class="task-fields hidden"><label class="wide">タイトル<input name="title" maxlength="160"></label><label>分類<select name="category">${CATEGORIES.map(v=>`<option>${v}</option>`).join("")}</select></label><label>温度感<select name="priority">${PRIORITIES.map(v=>`<option>${v}</option>`).join("")}</select></label><label>担当<input name="owner" maxlength="80" placeholder="任意"></label><label>開始日<input name="startDate" type="date"></label><label>期日<input name="dueDate" type="date"></label><label>想定所要時間（h）<input name="expectedHours" type="number" min="0" max="10000" step="0.25" inputmode="decimal" placeholder="例：1.5"></label><label class="wide">次の一手<textarea name="nextAction" rows="2" maxlength="500"></textarea></label><label class="wide">内容・備考<textarea name="notes" rows="4" maxlength="2000"></textarea></label></div><label class="continuous"><input name="continuous" type="checkbox" checked> 登録後も同じモードで続ける</label><button id="submitBtn" class="submit-btn" type="submit">登録して同期</button><p id="syncStatus" class="status" role="status">入力後、登録ボタンを押してください</p><button id="retryBtn" class="retry hidden" type="button">未送信を再同期</button></form></section></main>`;

const form=$("captureForm");
function readPending(){try{const value=JSON.parse(localStorage.getItem(DRAFT_KEY)||"[]");return Array.isArray(value)?value:[];}catch{return[];}}
function savePending(){localStorage.setItem(DRAFT_KEY,JSON.stringify(state.pending));updateRetry();}
function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=`quick-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`;localStorage.setItem(DEVICE_KEY,id);}return id;}
function tokyoDate(){return new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo"}).format(new Date());}
function newId(){const stamp=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(new Date()),p=Object.fromEntries(stamp.map(x=>[x.type,x.value])),suffix=(crypto.randomUUID?.()||Math.random().toString(36).slice(2)).replaceAll("-","").slice(0,8).toUpperCase();return`TSK-${p.year}${p.month}${p.day}-${p.hour}${p.minute}${p.second}-${suffix}`;}
function setStatus(type,text){$("syncStatus").className=`status ${type||""}`;$("syncStatus").textContent=text;}
function updateRetry(){$("retryBtn").classList.toggle("hidden",!state.pending.length);$("retryBtn").textContent=state.pending.length?`未送信 ${state.pending.length}件を再同期`:"未送信を再同期";}
function setMode(mode){state.mode=mode;$("choice").classList.add("hidden");$("capture").classList.remove("hidden");$("memoFields").classList.toggle("hidden",mode!=="memo");$("taskFields").classList.toggle("hidden",mode!=="task");$("modeTitle").textContent=mode==="memo"?"外部メモ":"タスク登録";$("modeGuide").textContent=mode==="memo"?"Microsoft To Doには同期されません":"TASK CONTROLの通常タスクとして登録します";form.elements.startDate.value=form.elements.startDate.value||tokyoDate();setStatus("","入力後、登録ボタンを押してください");setTimeout(()=>form.elements[mode==="memo"?"memo":"title"].focus(),30);}
function resetEntry(){if(state.mode==="memo")form.elements.memo.value="";else{const continuous=form.elements.continuous.checked,category=form.elements.category.value,priority=form.elements.priority.value,owner=form.elements.owner.value;form.reset();form.elements.continuous.checked=continuous;form.elements.category.value=category;form.elements.priority.value=priority;form.elements.owner.value=owner;form.elements.startDate.value=tokyoDate();}setTimeout(()=>form.elements[state.mode==="memo"?"memo":"title"].focus(),30);}
function makeRecord(){const now=new Date().toISOString();if(state.mode==="memo"){const memo=String(form.elements.memo.value||"").trim();if(!memo)throw new Error("メモを入力してください");return{id:newId(),category:"外部メモ",title:(memo.split(/\r?\n/).find(Boolean)||memo).slice(0,160),status:"未着手",priority:"🟠WARM",owner:"",startDate:tokyoDate(),dueDate:"",expectedMinutes:0,nextAction:"",notes:memo.slice(0,2000),now,device:deviceId()};}const title=String(form.elements.title.value||"").trim();if(!title)throw new Error("タイトルを入力してください");const startDate=form.elements.startDate.value,dueDate=form.elements.dueDate.value;if(startDate&&dueDate&&startDate>dueDate)throw new Error("期日は開始日以降を選択してください");return{id:newId(),category:form.elements.category.value||"その他",title,status:"未着手",priority:form.elements.priority.value||"🟠WARM",owner:String(form.elements.owner.value||"").trim(),startDate,dueDate,expectedMinutes:Math.max(0,Math.round((Number(form.elements.expectedHours.value)||0)*4)*15),nextAction:String(form.elements.nextAction.value||"").trim(),notes:String(form.elements.notes.value||"").trim(),now,device:deviceId()};}

async function initMsal(){if(!CONFIG?.CLIENT_ID||CONFIG.CLIENT_ID.includes("YOUR_")){setStatus("error","app-config.jsにCLIENT_IDを設定してください");return;}state.msal=new PublicClientApplication({auth:{clientId:CONFIG.CLIENT_ID,authority:CONFIG.AUTHORITY,redirectUri:CONFIG.REDIRECT_URI},cache:{cacheLocation:"localStorage"}});await state.msal.initialize();const redirect=await state.msal.handleRedirectPromise();state.account=redirect?.account||state.msal.getAllAccounts()[0]||null;if(state.account)state.msal.setActiveAccount(state.account);updateAccount();if(state.account&&state.pending.length)retryPending();}
async function login(){if(!state.msal)return;await state.msal.loginRedirect({scopes:SCOPES,prompt:"select_account"});}
async function token(){if(!state.account){await login();return null;}try{return(await state.msal.acquireTokenSilent({account:state.account,scopes:SCOPES})).accessToken;}catch(error){if(error instanceof InteractionRequiredAuthError){await state.msal.acquireTokenRedirect({account:state.account,scopes:SCOPES});return null;}throw error;}}
function updateAccount(){$("accountBtn").textContent=state.account?(state.account.username||"Microsoft接続済"):"Microsoftログイン";}
function graphError(response){const error=new Error(`OneDrive同期に失敗しました（HTTP ${response.status}）`);error.code=`GRAPH_${response.status}`;return error;}
function metaUrl(){return`https://graph.microsoft.com/v1.0/me/drive/special/approot:/${encodeURIComponent(WORKBOOK_FILE_NAME)}?$select=id,name,eTag,lastModifiedDateTime`;}
async function uploadRecord(record){const access=await token();if(!access)return false;for(let attempt=0;attempt<4;attempt++){const metaResponse=await fetch(metaUrl(),{headers:{Authorization:`Bearer ${access}`,Accept:"application/json"}});if(metaResponse.status===404)throw new Error("TASK_CONTROL_Master.xlsxがAppFolderにありません。先にTASK CONTROLでOneDrive同期してください");if(!metaResponse.ok)throw graphError(metaResponse);const meta=await metaResponse.json(),content=await fetch(`https://graph.microsoft.com/v1.0/me/drive/items/${encodeURIComponent(meta.id)}/content`,{headers:{Authorization:`Bearer ${access}`}});if(!content.ok)throw graphError(content);const next=await appendTaskRecord(await content.arrayBuffer(),record),upload=await fetch(`https://graph.microsoft.com/v1.0/me/drive/items/${encodeURIComponent(meta.id)}/content`,{method:"PUT",headers:{Authorization:`Bearer ${access}`,"Content-Type":WORKBOOK_MIME,"If-Match":meta.eTag},body:next});if(upload.ok)return true;if(upload.status===409||upload.status===412)continue;throw graphError(upload);}throw new Error("同時更新が続いたため登録できませんでした。再同期してください");}
async function sendRecord(record){setStatus("working","OneDrive同期中…");try{const ok=await uploadRecord(record);if(!ok)return false;setStatus("success",`✓ OneDrive同期完了｜${new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",hour:"2-digit",minute:"2-digit"}).format(new Date())}`);return true;}catch(error){if(!state.pending.some(item=>item.id===record.id)){state.pending.push(record);savePending();}setStatus("error",error.code==="GRAPH_423"?"Excel Masterを閉じて再同期してください":"端末内に一時保存しました。再同期できます");return false;}}
async function retryPending(){if(state.busy||!state.pending.length)return;state.busy=true;$("retryBtn").disabled=true;try{for(const record of[...state.pending]){if(!await uploadRecord(record))break;state.pending=state.pending.filter(item=>item.id!==record.id);savePending();}setStatus("success",state.pending.length?`未送信が${state.pending.length}件残っています`:`✓ 未送信をすべてOneDriveへ同期しました`);}catch(error){setStatus("error",error.code==="GRAPH_423"?"Excel Masterを閉じて再同期してください":"再同期できませんでした。入力内容は端末内に保持しています");}finally{state.busy=false;$("retryBtn").disabled=false;}}

document.querySelectorAll("[data-mode]").forEach(button=>button.onclick=()=>setMode(button.dataset.mode));
$("backBtn").onclick=()=>{$("capture").classList.add("hidden");$("choice").classList.remove("hidden");state.mode="";};
$("accountBtn").onclick=()=>state.account?login():login();$("retryBtn").onclick=retryPending;
form.onsubmit=async event=>{event.preventDefault();if(state.busy)return;let record;try{record=makeRecord();}catch(error){setStatus("error",error.message);return;}state.busy=true;$("submitBtn").disabled=true;const success=await sendRecord(record);state.busy=false;$("submitBtn").disabled=false;if(success){if(form.elements.continuous.checked)resetEntry();else $("backBtn").click();}};
window.addEventListener("online",()=>state.account&&state.pending.length&&retryPending());updateRetry();initMsal().catch(error=>setStatus("error",String(error.message||error)));
