import{PublicClientApplication,InteractionRequiredAuthError}from"@azure/msal-browser";
import{appendTaskRecord,readQuickCaptureTemplates,DEFAULT_QUICK_CAPTURE_TEMPLATES,WORKBOOK_FILE_NAME,WORKBOOK_MIME}from"./workbook-append.js";
import{syncMicrosoft,linkedRecords}from"./microsoft-sync.js";
import"./app-config.js";
import"./styles.css";

const CONFIG=window.QUICK_CAPTURE_CONFIG,SCOPES=CONFIG.GRAPH_SCOPES||["Files.ReadWrite.AppFolder"],DRAFT_KEY="quick-capture-pending-v1",DEVICE_KEY="quick-capture-device-v1",LOGIN_HINT_KEY="quick-capture-login-hint-v1",AUTO_LOGIN_KEY="quick-capture-auto-login-v11",TEMPLATE_CACHE_KEY="quick-capture-template-cache-v12";
const CATEGORIES=["防衛","収益","能力","構造","探索","ルーティン","その他"],PRIORITIES=["🔥HOT","🟠WARM","🧊COLD"];
const state={msal:null,account:null,mode:"",busy:false,templateBusy:false,pending:readPending(),templates:readTemplateCache(),templateSource:"cache"};
const $=id=>document.getElementById(id);

document.querySelector("#app").innerHTML=`<main class="app-shell"><header><div class="brand-mark">QC</div><div><h1>QUICK CAPTURE <small>V1.3</small></h1><p>TASK CONTROLへ送る</p></div><button id="accountBtn" class="account-btn" type="button">Microsoftログイン</button></header><section id="choice" class="choice"><button type="button" data-mode="memo"><span class="mode-icon">▤</span><b>メモ</b><small>外部メモとして送る</small></button><button type="button" data-mode="task"><span class="mode-icon">✓</span><b>タスク</b><small>必要項目を入力して送る</small></button></section><section id="capture" class="capture hidden"><div class="capture-head"><button id="backBtn" type="button" aria-label="戻る">←</button><div><h2 id="modeTitle"></h2><p id="modeGuide"></p></div></div><form id="captureForm"><div id="memoFields" class="memo-fields hidden"><label>メモ<textarea name="memo" rows="12" maxlength="2000" placeholder="ここにメモを入力"></textarea></label><section class="template-panel" aria-labelledby="templateTitle"><div class="template-heading"><h3 id="templateTitle">定形</h3><span id="templateStatus">Excel Master</span></div><div id="templateButtons" class="template-buttons"></div></section></div><div id="taskFields" class="task-fields hidden"><label class="wide">タイトル<input name="title" maxlength="160"></label><label>分類<select name="category">${CATEGORIES.map(v=>`<option>${v}</option>`).join("")}</select></label><label>温度感<select name="priority">${PRIORITIES.map(v=>`<option>${v}</option>`).join("")}</select></label><label>担当<input name="owner" maxlength="80" placeholder="任意"></label><label>開始日<input name="startDate" type="date"></label><label>期日<input name="dueDate" type="date"></label><label>想定所要時間（h）<input name="expectedHours" type="number" min="0" max="10000" step="0.25" inputmode="decimal" placeholder="例：1.5"></label><section class="wide integration-panel"><label class="continuous"><input name="reminderEnabled" type="checkbox"> Microsoft To Doのリマインダー</label><div id="reminderFields" class="hidden"><label>通知日時（日本時間）<input name="reminderAt" type="datetime-local"></label></div><label class="continuous"><input name="calendarEnabled" type="checkbox"> Outlookカレンダーへ予定登録</label><div id="calendarFields" class="task-fields hidden"><label>予定開始（日本時間）<input name="calendarStart" type="datetime-local"></label><label>予定終了（日本時間）<input name="calendarEnd" type="datetime-local"></label></div><p class="integration-guide">両方同時に設定できます。To Doへは通常タスクとして登録します。</p></section><label class="wide">次の一手<textarea name="nextAction" rows="2" maxlength="500"></textarea></label><label class="wide">内容・備考<textarea name="notes" rows="4" maxlength="2000"></textarea></label></div><label class="continuous"><input name="continuous" type="checkbox" checked> 登録後も同じモードで続ける</label><button id="submitBtn" class="submit-btn" type="submit">登録して同期</button><p id="syncStatus" class="status" role="status">入力後、登録ボタンを押してください</p><button id="retryBtn" class="retry hidden" type="button">未送信を再同期</button></form></section></main>`;

const form=$("captureForm");
function readPending(){try{const value=JSON.parse(localStorage.getItem(DRAFT_KEY)||"[]");return Array.isArray(value)?value:[];}catch{return[];}}
function readTemplateCache(){try{const raw=localStorage.getItem(TEMPLATE_CACHE_KEY);if(raw===null)return DEFAULT_QUICK_CAPTURE_TEMPLATES.map(item=>({...item}));const value=JSON.parse(raw);return Array.isArray(value)?value:DEFAULT_QUICK_CAPTURE_TEMPLATES.map(item=>({...item}));}catch{return DEFAULT_QUICK_CAPTURE_TEMPLATES.map(item=>({...item}));}}
function saveTemplateCache(){localStorage.setItem(TEMPLATE_CACHE_KEY,JSON.stringify(state.templates));}
function renderTemplates(){const buttons=$("templateButtons");if(!buttons)return;buttons.innerHTML=state.templates.length?state.templates.map(item=>`<button type="button" data-template-id="${String(item.id).replaceAll('"','&quot;')}">${String(item.name).replaceAll("&","&amp;").replaceAll("<","&lt;")}</button>`).join(""):`<p class="template-empty">有効な定形はありません</p>`;$("templateStatus").textContent=state.templateSource==="master"?"Excel Masterと同期済":"内蔵／保存済み定形";}
function insertTemplate(item){const field=form.elements.memo,current=String(field.value||"");if(current.trim()===item.body.trim()){field.focus();return;}const separator=current&&!current.endsWith("\n")?"\n\n":"";field.value=`${current}${separator}${item.body}`.slice(0,field.maxLength||2000);field.focus();const firstBlank=field.value.indexOf("：")+1;const cursor=firstBlank>0?firstBlank:field.value.length;field.setSelectionRange(cursor,cursor);document.querySelectorAll("[data-template-id]").forEach(button=>button.classList.toggle("active",button.dataset.templateId===item.id));}
function savePending(){localStorage.setItem(DRAFT_KEY,JSON.stringify(state.pending));updateRetry();}
function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=`quick-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`;localStorage.setItem(DEVICE_KEY,id);}return id;}
function tokyoDate(){return new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo"}).format(new Date());}
function newId(){const stamp=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(new Date()),p=Object.fromEntries(stamp.map(x=>[x.type,x.value])),suffix=(crypto.randomUUID?.()||Math.random().toString(36).slice(2)).replaceAll("-","").slice(0,8).toUpperCase();return`TSK-${p.year}${p.month}${p.day}-${p.hour}${p.minute}${p.second}-${suffix}`;}
function setStatus(type,text){$("syncStatus").className=`status ${type||""}`;$("syncStatus").textContent=text;}
function updateRetry(){$("retryBtn").classList.toggle("hidden",!state.pending.length);$("retryBtn").textContent=state.pending.length?`未送信 ${state.pending.length}件を再同期`:"未送信を再同期";}
function setMode(mode){state.mode=mode;$("choice").classList.add("hidden");$("capture").classList.remove("hidden");$("memoFields").classList.toggle("hidden",mode!=="memo");$("taskFields").classList.toggle("hidden",mode!=="task");$("modeTitle").textContent=mode==="memo"?"外部メモ":"タスク登録";$("modeGuide").textContent=mode==="memo"?"Microsoft To Doには同期されません":"TASK CONTROLの通常タスクとして登録します";form.elements.startDate.value=form.elements.startDate.value||tokyoDate();updateIntegrationEditor();setStatus("","入力後、登録ボタンを押してください");if(mode==="memo")refreshTemplates();setTimeout(()=>form.elements[mode==="memo"?"memo":"title"].focus(),30);}
function updateIntegrationEditor(){for(const [toggle,fields,names]of[["reminderEnabled","reminderFields",["reminderAt"]],["calendarEnabled","calendarFields",["calendarStart","calendarEnd"]]]){const enabled=state.mode==="task"&&form.elements[toggle].checked;$(fields).classList.toggle("hidden",!enabled);for(const name of names){form.elements[name].disabled=!enabled;form.elements[name].required=enabled;}}}
function resetEntry(){if(state.mode==="memo")form.elements.memo.value="";else{const continuous=form.elements.continuous.checked,category=form.elements.category.value,priority=form.elements.priority.value,owner=form.elements.owner.value;form.reset();form.elements.continuous.checked=continuous;form.elements.category.value=category;form.elements.priority.value=priority;form.elements.owner.value=owner;form.elements.startDate.value=tokyoDate();}updateIntegrationEditor();setTimeout(()=>form.elements[state.mode==="memo"?"memo":"title"].focus(),30);}
function makeRecord(){const now=new Date().toISOString();if(state.mode==="memo"){const memo=String(form.elements.memo.value||"").trim();if(!memo)throw new Error("メモを入力してください");return{id:newId(),category:"外部メモ",title:(memo.split(/\r?\n/).find(Boolean)||memo).slice(0,160),status:"未着手",priority:"🟠WARM",owner:"",startDate:tokyoDate(),dueDate:"",expectedMinutes:0,nextAction:"",notes:memo.slice(0,2000),now,device:deviceId()};}const title=String(form.elements.title.value||"").trim();if(!title)throw new Error("タイトルを入力してください");const startDate=form.elements.startDate.value,dueDate=form.elements.dueDate.value;if(startDate&&dueDate&&startDate>dueDate)throw new Error("期日は開始日以降を選択してください");const reminderAt=form.elements.reminderEnabled.checked?form.elements.reminderAt.value:"",calendarEnabled=form.elements.calendarEnabled.checked,calendarStart=calendarEnabled?form.elements.calendarStart.value:"",calendarEnd=calendarEnabled?form.elements.calendarEnd.value:"";if(form.elements.reminderEnabled.checked&&(!reminderAt||!Number.isFinite(Date.parse(`${reminderAt}:00+09:00`))||Date.parse(`${reminderAt}:00+09:00`)<=Date.now()))throw new Error("リマインダーは現在より後の日時を設定してください");if(calendarEnabled&&(!calendarStart||!calendarEnd||calendarStart>=calendarEnd))throw new Error("予定終了は予定開始より後に設定してください");return{reminderAt,calendarEnabled,calendarStart,calendarEnd,calendarTransactionId:crypto.randomUUID(),id:newId(),category:form.elements.category.value||"その他",title,status:"未着手",priority:form.elements.priority.value||"🟠WARM",owner:String(form.elements.owner.value||"").trim(),startDate,dueDate,expectedMinutes:Math.max(0,Math.round((Number(form.elements.expectedHours.value)||0)*4)*15),nextAction:String(form.elements.nextAction.value||"").trim(),notes:String(form.elements.notes.value||"").trim(),now,device:deviceId()};}

async function initMsal(){if(!CONFIG?.CLIENT_ID||CONFIG.CLIENT_ID.includes("YOUR_")){setStatus("error","app-config.jsにCLIENT_IDを設定してください");return;}state.msal=new PublicClientApplication({auth:{clientId:CONFIG.CLIENT_ID,authority:CONFIG.AUTHORITY,redirectUri:CONFIG.REDIRECT_URI,navigateToLoginRequestUrl:false},cache:{cacheLocation:"localStorage",storeAuthStateInCookie:true}});await state.msal.initialize();let redirect=null;try{redirect=await state.msal.handleRedirectPromise();}catch(error){if(!/login_required|interaction_required|consent_required|no_session/i.test(`${error.errorCode||""} ${error.message||""}`))throw error;}state.account=redirect?.account||state.msal.getAllAccounts()[0]||null;if(state.account){sessionStorage.removeItem(AUTO_LOGIN_KEY);state.msal.setActiveAccount(state.account);localStorage.setItem(LOGIN_HINT_KEY,state.account.username||"");updateAccount();if(state.pending.length)retryPending();return;}updateAccount();if(sessionStorage.getItem(AUTO_LOGIN_KEY)!=="attempted"){sessionStorage.setItem(AUTO_LOGIN_KEY,"attempted");setStatus("working","Microsoft自動接続中…");await state.msal.loginRedirect({scopes:SCOPES,prompt:"none",redirectUri:CONFIG.REDIRECT_URI,loginHint:localStorage.getItem(LOGIN_HINT_KEY)||undefined});}}
async function login(){if(!state.msal)return;sessionStorage.removeItem(AUTO_LOGIN_KEY);await state.msal.loginRedirect({scopes:SCOPES,prompt:"select_account",redirectUri:CONFIG.REDIRECT_URI,loginHint:localStorage.getItem(LOGIN_HINT_KEY)||undefined});}
async function token(scopes=SCOPES){if(!state.account){await login();return null;}try{return(await state.msal.acquireTokenSilent({account:state.account,scopes})).accessToken;}catch(error){if(error instanceof InteractionRequiredAuthError){await state.msal.acquireTokenRedirect({account:state.account,scopes});return null;}throw error;}}
function updateAccount(){$("accountBtn").textContent=state.account?(state.account.username||"Microsoft接続済"):"Microsoftログイン";}
function graphError(response){const error=new Error(`OneDrive同期に失敗しました（HTTP ${response.status}）`);error.code=`GRAPH_${response.status}`;return error;}
function metaUrl(){return`https://graph.microsoft.com/v1.0/me/drive/special/approot:/${encodeURIComponent(WORKBOOK_FILE_NAME)}?$select=id,name,eTag,lastModifiedDateTime`;}
async function refreshTemplates(){if(!state.account||state.templateBusy)return;state.templateBusy=true;try{const access=await token();if(!access)return;const metaResponse=await fetch(metaUrl(),{headers:{Authorization:`Bearer ${access}`,Accept:"application/json"}});if(!metaResponse.ok)return;const meta=await metaResponse.json(),content=await fetch(`https://graph.microsoft.com/v1.0/me/drive/items/${encodeURIComponent(meta.id)}/content`,{headers:{Authorization:`Bearer ${access}`}});if(!content.ok)return;state.templates=await readQuickCaptureTemplates(await content.arrayBuffer());state.templateSource="master";saveTemplateCache();renderTemplates();}catch{}finally{state.templateBusy=false;}}
async function uploadRecord(record){const access=await token();if(!access)return false;for(let attempt=0;attempt<4;attempt++){const metaResponse=await fetch(metaUrl(),{headers:{Authorization:`Bearer ${access}`,Accept:"application/json"}});if(metaResponse.status===404)throw new Error("TASK_CONTROL_Master.xlsxがAppFolderにありません。先にTASK CONTROLでOneDrive同期してください");if(!metaResponse.ok)throw graphError(metaResponse);const meta=await metaResponse.json(),content=await fetch(`https://graph.microsoft.com/v1.0/me/drive/items/${encodeURIComponent(meta.id)}/content`,{headers:{Authorization:`Bearer ${access}`}});if(!content.ok)throw graphError(content);const bytes=await content.arrayBuffer();state.templates=await readQuickCaptureTemplates(bytes);state.templateSource="master";saveTemplateCache();renderTemplates();const next=await appendTaskRecord(bytes,record,linkedRecords(record)),upload=await fetch(`https://graph.microsoft.com/v1.0/me/drive/items/${encodeURIComponent(meta.id)}/content`,{method:"PUT",headers:{Authorization:`Bearer ${access}`,"Content-Type":WORKBOOK_MIME,"If-Match":meta.eTag},body:next});if(upload.ok)return true;if(upload.status===409||upload.status===412)continue;throw graphError(upload);}throw new Error("同時更新が続いたため登録できませんでした。再同期してください");}
function queueRecord(record){if(!state.pending.some(item=>item.id===record.id))state.pending.push(record);savePending();}
async function processRecord(record){if(!state.account){await login();return false;}const access=await token();if(!access)return false;const meta=await fetch(metaUrl(),{headers:{Authorization:`Bearer ${access}`}});if(meta.status===404)throw new Error("先にTASK CONTROLでOneDrive同期し、Masterを作成してください");if(!meta.ok)throw graphError(meta);if(!await syncMicrosoft(record,token,savePending,text=>setStatus("working",text)))return false;setStatus("working","OneDrive同期中…");if(!await uploadRecord(record))return false;state.pending=state.pending.filter(item=>item.id!==record.id);savePending();return true;}
async function sendRecord(record){queueRecord(record);try{const ok=await processRecord(record);if(!ok)return false;setStatus("success",record.category==="外部メモ"?"✓ OneDrive同期完了":`✓ OneDrive・To Do登録完了${record.calendarEnabled?"・Outlook予定登録完了":""}`);return true;}catch(error){setStatus("error",`${error.message}｜入力は端末内に保持しています。「未送信を再同期」で続行できます。`);return false;}}
async function retryPending(){if(state.busy||!state.pending.length)return;state.busy=true;setBusy(true);try{for(const record of [...state.pending]){if(!await processRecord(record))return;}setStatus("success","✓ 未送信をすべて同期しました");}catch(error){setStatus("error",`${error.message}｜入力は端末内に保持しています。`);}finally{state.busy=false;setBusy(false);}}
function setBusy(busy){$("submitBtn").disabled=busy;$("retryBtn").disabled=busy;$("backBtn").disabled=busy;$("accountBtn").disabled=busy;}

document.querySelectorAll("[data-mode]").forEach(button=>button.onclick=()=>setMode(button.dataset.mode));
$("templateButtons").onclick=event=>{const button=event.target.closest("[data-template-id]");if(!button)return;const item=state.templates.find(template=>template.id===button.dataset.templateId);if(item)insertTemplate(item);};
$("backBtn").onclick=()=>{$("capture").classList.add("hidden");$("choice").classList.remove("hidden");state.mode="";};
$("accountBtn").onclick=()=>state.account?login():login();$("retryBtn").onclick=retryPending;
form.onsubmit=async event=>{event.preventDefault();if(state.busy)return;let record;try{record=makeRecord();}catch(error){setStatus("error",error.message);return;}state.busy=true;setBusy(true);const success=await sendRecord(record);state.busy=false;setBusy(false);if(success){if(form.elements.continuous.checked)resetEntry();else $("backBtn").click();}else resetEntry();};
form.elements.reminderEnabled.onchange=updateIntegrationEditor;form.elements.calendarEnabled.onchange=updateIntegrationEditor;
window.addEventListener("online",()=>{if(state.account){refreshTemplates();if(state.pending.length)retryPending();}});renderTemplates();updateRetry();initMsal().then(()=>refreshTemplates()).catch(error=>setStatus("error",String(error.message||error)));
