export const TRELLO_LISTS=Object.freeze({today:"6ac10bd1ca0b5a456dea73c6",soon:"6ac10bd411f9c9725362a9ea",due:"6ac10bd7fd7e073bddb447dc",caution:"6ac10bd9b13017ef2df8f34f",inbox:"6ac10bdcb81d10d935e50045"});
export const TRELLO_LIST_OPTIONS=[[TRELLO_LISTS.today,"今日やること"],[TRELLO_LISTS.soon,"今週〜近々やること"],[TRELLO_LISTS.due,"納期 / 期日管理"],[TRELLO_LISTS.caution,"要注意事項"],[TRELLO_LISTS.inbox,"INBOX"]];
const LABELS={external:"65b3b700c2275bca1c9b6185",internal:"65b3b7027090b042bc891d22"},SETTINGS_KEY="quick-capture-trello-settings-v14";
export function trelloSettings(){try{const value=JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}");return{key:String(value.key||"").trim(),token:String(value.token||"").trim()};}catch{return{key:"",token:""};}}
export function saveTrelloSettings(value){localStorage.setItem(SETTINGS_KEY,JSON.stringify({key:String(value.key||"").trim(),token:String(value.token||"").trim()}));}
export function clearTrelloSettings(){localStorage.removeItem(SETTINGS_KEY);}
export function trelloConfigured(){const value=trelloSettings();return Boolean(value.key&&value.token);}
export function trelloDescriptionDefault(task){return[["次の一手",task.nextAction],["メモ",task.notes]].filter(([,value])=>String(value||"").trim()).map(([label,value])=>`【${label}】\n${String(value).trim()}`).join("\n\n");}
async function request(path,{method="GET",query={},body}={}){const settings=trelloSettings();if(!settings.key||!settings.token)throw new Error("Trello接続設定にAPI Key / User Tokenを保存してください");const url=new URL(`https://api.trello.com/1/${path}`);url.searchParams.set("key",settings.key);url.searchParams.set("token",settings.token);for(const[k,v]of Object.entries(query))url.searchParams.set(k,String(v));let response;try{response=await fetch(url,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});}catch{throw new Error("Trelloへ接続できません。通信状態を確認して再同期してください");}let payload;try{payload=await response.json();}catch{}if(!response.ok)throw new Error(`Trello ${response.status}：${response.status===401||response.status===403?"API Key / User Tokenとボードへのアクセス権を確認してください":response.status===429?"時間を置いて再同期してください":"登録できませんでした。共有先と入力内容を確認してください"}`);return payload;}
export async function testTrelloConnection(){return request("members/me",{query:{fields:"id,username,fullName"}});}
const marker=(record,role)=>`TASK CONTROL TaskID: ${record.id} / ${role}`;
export function trelloCardBody(record,listId,role){const value=record.trello;return{idList:listId,pos:"bottom",name:value.title||record.title,desc:[value.description,String(value.owner||"").trim()?`担当：${String(value.owner).trim()}`:"",marker(record,role)].filter(Boolean).join("\n\n"),due:value.dueDate?`${value.dueDate}T23:59:00+09:00`:null,idLabels:value.label?[LABELS[value.label]]:[]};}
async function ensureCard(record,listId,role,idField,checkpoint){const value=record.trello;if(value[idField])return;
 const list=await request(`lists/${encodeURIComponent(listId)}`,{query:{fields:"id,idBoard,closed"}});if(list.closed)throw new Error("Trelloの共有先リストがアーカイブされています");
 const cards=await request(`boards/${encodeURIComponent(list.idBoard)}/cards`,{query:{fields:"id,desc,closed",filter:"all"}}),signature=marker(record,role),existing=cards.find(card=>String(card.desc||"").split(/\r?\n/).includes(signature));
 if(existing?.closed)throw new Error("登録済みのTrelloカードがアーカイブされています。Trelloで復元して再同期してください");
 const card=existing||await request("cards",{method:"POST",body:trelloCardBody(record,listId,role)});if(!card?.id)throw new Error("TrelloカードIDを確認できませんでした。再同期してください");value[idField]=card.id;checkpoint();
}
export async function syncTrello(record,checkpoint,status){if(record.category==="外部メモ"||!record.trello?.enabled||record.trelloDone)return true;if(!trelloConfigured())throw new Error("Trello接続設定にAPI Key / User Tokenを保存してください");const value=record.trello;if(!TRELLO_LIST_OPTIONS.some(([id])=>id===value.listId))throw new Error("Trello共有先リストを確認してください");status("Trelloカード登録中…");await ensureCard(record,value.listId,"MAIN","cardId",checkpoint);if(value.dueCopy&&value.listId!==TRELLO_LISTS.due)await ensureCard(record,TRELLO_LISTS.due,"DUE","dueCardId",checkpoint);value.status="共有済み";value.error="";record.trelloDone=true;checkpoint();return true;}
export function trelloLinkedRecords(record){if(record.category==="外部メモ"||!record.trello?.enabled||!record.trello.cardId)return[];const id=`ZZZ-TC-TRELLO-${record.id}`,value=record.trello;return[{id,rootId:id,sortOrder:0,category:"その他",title:`Trello共有｜${record.id}`,status:"完了",priority:"🧊COLD",owner:"",startDate:"",dueDate:"",progress:100,nextAction:"",blocker:"",notes:JSON.stringify({enabled:true,listId:value.listId,title:value.title||record.title,description:value.description||"",owner:value.owner||"",dueDate:value.dueDate||"",label:value.label||"",dueCopy:Boolean(value.dueCopy),cardId:value.cardId,dueCardId:value.dueCardId||"",status:value.status||"共有済み",error:""}),linkUrl:"",now:record.now,device:record.device}];}
